package com.wiley;

public class CdMain {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ArrangeCd arrange = new ArrangeCd();
		arrange.enter();
		arrange.display();																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																			
	}

}
